require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'ext/**/*'
    - 'benchmark/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

# Disable because we can't properly document the module_eval with current syntax
Style/DocumentDynamicEvalDefinition:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/type_balancer.rb'
    - 'lib/type_balancer/balancer.rb'
    - 'lib/type_balancer/pure_ruby_calculator.rb'

# Add exceptions for our complex balancing algorithms
Metrics/AbcSize:
  Exclude:
    - 'lib/type_balancer.rb'
    - 'lib/type_balancer/balancer.rb'
    - 'lib/type_balancer/pure_ruby_calculator.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/type_balancer.rb'
    - 'lib/type_balancer/balancer.rb'
    - 'lib/type_balancer/pure_ruby_calculator.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/type_balancer.rb'
    - 'lib/type_balancer/balancer.rb'
    - 'lib/type_balancer/pure_ruby_calculator.rb'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/RepeatedExample:
  Enabled: false  # We have intentionally repeated examples

# Disable all Capybara/RSpec cops
Capybara/RSpec:
  Enabled: false

# Disable all RSpec/Capybara cops
RSpec/Capybara:
  Enabled: false

# Disable all RSpec/FactoryBot cops
RSpec/FactoryBot:
  Enabled: false

# Disable all RSpec/Rails cops
RSpec/Rails:
  Enabled: false

# Disable PredicateMatcher cop that's causing errors
RSpec/PredicateMatcher:
  Enabled: false