require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'ext/**/*'
    - 'benchmark/**/*'
    - 'vendor/**/*'
    - 'examples/quality.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/type_balancer/distributor.rb'
    - 'lib/type_balancer/balancer.rb'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/type_balancer/distributor.rb'
    - 'lib/type_balancer/balancer.rb'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/type_balancer/distributor.rb'
    - 'lib/type_balancer/balancer.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'lib/type_balancer/distributor.rb'
    - 'lib/type_balancer/balancer.rb'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/RepeatedExample:
  Enabled: false  # We have intentionally repeated examples

RSpec/MultipleDescribes:
  Enabled: false  # We have intentionally structured our specs this way

RSpec/RepeatedExampleGroupDescription:
  Enabled: false  # We have intentionally structured our specs this way

# Disable all Capybara/RSpec cops
Capybara/RSpec:
  Enabled: false

# Disable all RSpec/Capybara cops
RSpec/Capybara:
  Enabled: false

# Disable all RSpec/FactoryBot cops
RSpec/FactoryBot:
  Enabled: false

# Disable all RSpec/Rails cops
RSpec/Rails:
  Enabled: false

# Disable PredicateMatcher cop that's causing errors
RSpec/PredicateMatcher:
  Enabled: false

Style/HashExcept:
  Enabled: false