require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/RepeatedExample:
  Enabled: false  # We have intentionally repeated examples

# Disable all Capybara/RSpec cops
Capybara/RSpec:
  Enabled: false

# Disable all RSpec/Capybara cops
RSpec/Capybara:
  Enabled: false

# Disable all RSpec/FactoryBot cops
RSpec/FactoryBot:
  Enabled: false

# Disable all RSpec/Rails cops
RSpec/Rails:
  Enabled: false

# Disable PredicateMatcher cop that's causing errors
RSpec/PredicateMatcher:
  Enabled: false