name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec:
    name: RSpec Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only testing Ruby versions that support YJIT (3.2+)
        ruby-version: ['3.2.8', '3.3.7', '3.4.2']
        yjit: ['disabled']
        # Add YJIT enabled configuration for all versions
        include:
          - ruby-version: '3.2.8'
            yjit: 'enabled'
          - ruby-version: '3.3.7'
            yjit: 'enabled'
          - ruby-version: '3.4.2'
            yjit: 'enabled'

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      
      - name: Run tests with coverage
        run: bundle exec rspec
        env:
          COVERAGE: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          RUBY_YJIT_ENABLE: ${{ matrix.yjit == 'enabled' && 'true' || 'false' }}

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-ruby-${{ matrix.ruby-version }}-yjit-${{ matrix.yjit }}
          path: coverage
          retention-days: 14

  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true
      
      - name: Install steep
        run: gem install steep
      
      - name: Run type check
        run: steep check

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true
      
      - name: Run RuboCop
        run: bundle exec rubocop

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true
      
      - name: Install bundler-audit
        run: gem install bundler-audit
      
      - name: Check for vulnerable dependencies
        run: bundle-audit check --update

  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true
      
      - name: Run quality checks
        run: ruby examples/quality.rb 