name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec:
    name: RSpec Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Adjusting Ruby versions based on our gemspec requirement
        ruby-version: ['3.1', '3.2', '3.3']

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      
      - name: Run tests with coverage
        run: bundle exec rspec

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      
      - name: Run RuboCop
        run: bundle exec rubocop

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      
      - name: Install bundler-audit
        run: gem install bundler-audit
      
      - name: Check for vulnerable dependencies
        run: bundle-audit check --update 